const PDFDocument = require('pdfkit')
const fs = require('fs')
const path = require('path')

const outPath = path.join(__dirname, '..', 'guia_teste.pdf')
const doc = new PDFDocument({ margin: 50 })
doc.pipe(fs.createWriteStream(outPath))

doc.fontSize(20).text('Guia de Teste', { align: 'left' })
doc.moveDown()

doc.fontSize(12).text('Composes: subir, reiniciar e deixar cair', { underline: true })
doc.moveDown(0.5)
doc.fontSize(11).text('docker compose -f docker-compose.yml -f docker-compose.s3.yml -f docker-compose-replica.yml -f docker-compose-haproxy.yml up -d')
doc.text('docker compose -f docker-compose.yml -f docker-compose.s3.yml -f docker-compose-replica.yml -f docker-compose-haproxy.yml restart')
doc.text('docker compose -f docker-compose.yml -f docker-compose.s3.yml -f docker-compose-replica.yml -f docker-compose-haproxy.yml down')
doc.text('docker ps --format \'{{.Names}}\\t{{.Status}}\'')
doc.moveDown()

doc.fontSize(12).text('Composes Instância 2: subir, reiniciar e deixar cair', { underline: true })
doc.moveDown(0.5)
doc.fontSize(11).text('docker compose -f docker-compose-app2.yml up -d')
doc.text('docker compose -f docker-compose-app2.yml restart')
doc.text('docker compose -f docker-compose-app2.yml down')
doc.moveDown()

doc.fontSize(12).text('Failover: promover standby → primary', { underline: true })
doc.moveDown(0.5)
doc.fontSize(11).text('psql -h localhost -p 5555 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.text('psql -h localhost -p 5556 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.text('psql -h localhost -p 5555 -U supabase_admin -d postgres -c \"select pg_promote(wait => true);\"')
doc.text('psql -h localhost -p 5556 -U supabase_admin -d postgres -c \"select pg_promote(wait => true);\"')
doc.text('psql -h localhost -p 5555 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.text('psql -h localhost -p 5556 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.moveDown()

doc.fontSize(12).text('Fallback: voltar ao primary original', { underline: true })
doc.moveDown(0.5)
doc.fontSize(11).text('psql -h localhost -p 5555 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.text('psql -h localhost -p 5556 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.text('docker restart supabase-db-replica')
doc.text('psql -h localhost -p 5555 -U supabase_admin -d postgres -c \"select pg_promote(wait => true);\"')
doc.text('psql -h localhost -p 5556 -U supabase_admin -d postgres -c \"select pg_promote(wait => true);\"')
doc.text('psql -h localhost -p 5555 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.text('psql -h localhost -p 5556 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.moveDown(1.5)

doc.fontSize(12).text('Passos: Teste de Failover', { underline: true })
doc.moveDown(0.5)
doc.fontSize(11).text('1) psql -h localhost -p 5555 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.text('2) psql -h localhost -p 5556 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.text('3) (no nó em recuperação) psql -h localhost -p <porta> -U supabase_admin -d postgres -c \"select pg_promote(wait => true);\"')
doc.text('4) Confirmar estados com pg_is_in_recovery() nas duas portas')
doc.moveDown()

doc.fontSize(12).text('Passos: Teste de Failback', { underline: true })
doc.moveDown(0.5)
doc.fontSize(11).text('1) docker restart supabase-db-replica')
doc.text('2) psql -h localhost -p 5555 -U supabase_admin -d postgres -c \"select pg_promote(wait => true);\"')
doc.text('3) Validar: 5555 = not in recovery, 5556 = in recovery')
doc.text('4) psql -h localhost -p 5555 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.text('5) psql -h localhost -p 5556 -U supabase_admin -d postgres -tAc \"select pg_is_in_recovery();\"')
doc.moveDown()

doc.fontSize(12).text('Saúde dos containers', { underline: true })
doc.moveDown(0.5)
doc.fontSize(11).text('docker ps --format \'{{.Names}}\\t{{.Status}}\'')
doc.text('curl -i \"http://localhost:8000/auth/v1/health\"')
doc.text('curl -i \"http://localhost:8001/auth/v1/health\"')
doc.text('curl -i -H \"apikey: $ANON_KEY\" \"http://localhost:8000/rest/v1/\"')
doc.text('curl -i -H \"apikey: $ANON_KEY\" \"http://localhost:8001/rest/v1/\"')
doc.text('curl -i \"http://localhost:8000/storage/v1/status\"')
doc.text('curl -i \"http://localhost:8001/storage/v1/status\"')
doc.text('curl -i \"http://localhost:8000/realtime/v1/api\"')
doc.text('curl -i \"http://localhost:8001/realtime/v1/api\"')
doc.moveDown()

doc.fontSize(12).text('Operações por compose', { underline: true })
doc.moveDown(0.5)
doc.fontSize(11).text('- Principal:')
doc.text('  docker compose -f docker-compose.yml -f docker-compose.s3.yml -f docker-compose-replica.yml -f docker-compose-haproxy.yml up -d')
doc.text('  docker compose -f docker-compose.yml -f docker-compose.s3.yml -f docker-compose-replica.yml -f docker-compose-haproxy.yml down')
doc.text('  docker compose -f docker-compose.yml -f docker-compose.s3.yml -f docker-compose-replica.yml -f docker-compose-haproxy.yml restart')
doc.text('- Instância 2:')
doc.text('  docker compose -f docker-compose-app2.yml up -d')
doc.text('  docker compose -f docker-compose-app2.yml down')
doc.text('  docker compose -f docker-compose-app2.yml restart')
doc.moveDown()

doc.fontSize(12).text('Operações por container', { underline: true })
doc.moveDown(0.5)
doc.fontSize(11).text('docker start <container>')
doc.text('docker stop <container>')
doc.text('docker restart <container>')
doc.text('docker logs --tail 200 <container>')
doc.text('for c in supabase-auth supabase-auth-2 supabase-rest rest-2 supabase-kong supabase-kong-2 supabase-db supabase-db-replica supabase-storage supabase-storage-2 realtime-dev.supabase-realtime realtime-2 analytics analytics-2; do docker restart \"$c\"; done')
doc.moveDown(1.5)

doc.fontSize(10).text('MyKondo • Ambiente local Supabase HA • Data de geração: ' + new Date().toISOString())

doc.end()
